apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: worker
    tier: back
  name: worker
spec:
  replicas: 1
  template:
    spec:
      $setElementOrder/containers:
      - name: worker
      containers:
      - image: schoolofdevops/worker:v1
        name: worker
